export const fonts = [
    "Inter",
    "Roboto",
    "Roboto Flex",
    "Roboto Serif",
    "Roboto Mono",
    "Poppins",
    "Open Sans",
    "Lato",
    "Playfair Display",
    "Pacifico",
    "Electrolize",
    "Comic Neue",
    "Bebas Neue",
  ];